eureka:
  client:
    service-url:
      defaultZone: http://registry-server-3:8761/eureka/,http://registry-server-2:8760/eureka/,http://registry-server-1:8759/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
#  zipkin:
#    base-url: http://localhost:8750/
  rabbitmq:
    username: rabbit
    password: 123456
feign:
  hystrix:
    enabled: true
