version: '2'
services:
  mq:
    image: rabbitmq:3.6.10-management-alpine
    environment:
      - "RABBITMQ_DEFAULT_USER=rabbit"
      - "RABBITMQ_DEFAULT_PASS=123456"
    networks:
      - scd-net
    ports:
      - "15672:15672"
    container_name: demo-mq
  mysql:
    image: mysql:5.7.18
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
    ports:
      - "3306:3306"
    networks:
      - scd-net
    container_name: demo-mysql
  redis:
    image: redis:3.2.10-alpine
    ports:
      - "6379:6379"
    networks:
      - scd-net
    container_name: demo-redis
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
    networks:
      - scd-net
  jenkins:
    image: 'jenkins/jenkins:lts'
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - 'jenkins-data:/var/jenkins_home'
    networks:
      - scd-net
networks:
  scd-net:
    driver: bridge
volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkins-data: