spring:
  profiles:
    active: dev
  application:
    name: service-mail

---
spring:
  profiles: dev
  mail:
    host: smtp.qq.com
    username: wolfxz@vip.qq.com
    password: "#xu$zhen>2016?2"
    properties:
      mail:
        smtp:
          auth: true
          port: 465
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
eureka:
  client:
    service-url:
      default-zone: http://registry-server-3:8761/eureka/,http://registry-server-2:8760/eureka/,http://registry-server-1:8759/eureka/
server:
  port: 8874