eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-server-3:8761/eureka/,http://registry-server-2:8760/eureka/,http://registry-server-1:8759/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
management:
  security:
    enabled: false